# Generated by Django 3.1.1 on 2020-09-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200925_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='creted',
            new_name='created',
        ),
    ]
